services:
  postgres:
    image: postgres:16
    container_name: voting-postgres
    environment:
      POSTGRES_DB: voting_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - voting-postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend/Voting.Api
      dockerfile: Dockerfile
    container_name: voting-api
    depends_on:
      - postgres
    ports:
      - "5163:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=voting_platform;Username=postgres;Password=postgres
      Jwt__Key: ${JWT_Secret}
      Jwt__Issuer: Voting.Api
      Jwt__Audience: Voting.Frontend
      Cors__AllowedOrigins__0: http://localhost:5173
      Email__Provider: Smtp
      Email__SmtpHost: smtp.gmail.com
      Email__SmtpPort: 587
      Email__SmtpUsername: ${SMTP_USERNAME}
      Email__SmtpPassword: ${SMTP_PASSWORD}
      Email__SenderEmail: ${SMTP_SENDER_EMAIL}
      Email__SenderName: Voting Platform
      Email__SmtpUseStartTls: true

volumes:
  voting-postgres-data:
